### PR TITLE
add remember me credentials

### PR DESCRIPTION
**Pull request by navin9584**
add remember me functionality
1. when remember me switch on then after logout schoolid & password auto save 
2.  when remember me switch off then schoolid & password field should be empty 
3. need to check by switch school

### CODE REVIEW

**Comment by apurvabisht97** [comment]
when we login with first school and try to on the remember button in screen it is saving first school credentials. when i do logout from school and again go back to login page i am able to see first school data already filled that is the expected working of remember  me credentials . When I try to login with second school my remember button is already on . So we need to overwrite first school credentials with second school . This is currently missing in this pr .

**Comment by navin9584** [comment]
i have changed in functionality like if we login with first school and do remember me on then after logout it will auto save ,
if we login with second school then after logout fileld will empty because credential save for first school , now fill fields for school 2 and do remember me on after logout you will see for school 2 credential @apurvabisht97 @dileep-gadiraju

**Comment by apurvabisht97** [comment]
after logout of second school it should not be empty it should save second school data . @navin9584

**Comment by apurvabisht97** [comment]
hi @dileep-gadiraju  i have done testing of above pr . it is working as expected .

**Review by dileep-gadiraju — APPROVED** [review]

**Pull request merged**
