### PR TITLE
offline storage features

### PR DESCRIPTION
**Pull request by apurvabisht97**

### CODE REVIEW

**Review by navin9584 — COMMENTED** [review]
found one issue in minimal mode 
1. If we have multiple layout and we want to store multiple layout cache but we are able to store cache of only one layout now

**Comment by apurvabisht97** [comment]
absent/present issue found on this pr ..... when i am login to one school and going to class sec and subject if i mark any student absent on one subject that student is showing absent on other subject as well .

**Comment by apurvabisht97** [comment]
issue cache is not working for class/sec and subject .... getting alert message in offline mode

**Comment by apurvabisht97** [comment]
Hi @dileep-gadiraju ... i have tested above pr it is working fine

**Pull request merged**
