### PR TITLE
Feature/demo fb

### PR DESCRIPTION
**Pull request by arman-tdev**

### CODE REVIEW

**Comment by navin9584** [comment]
@dileep-gadiraju @harish-challa @arman-tdev  i have tested this pr and my finding is 
**isFBDownloadEnable is true** then
When I am installing the app for the first time then I am getting the flag true but when I  reopen  app again then the flag is getting false and model not available popup is showing. 
it is not working proper

**Comment by dileep-gadiraju** [comment]
Hi @arman-tdev / @navin9584   cc: @harish-challa 

Please have a call to see why it's not working when Naivn is testing. we need to test on multiple devices and emulators to make sure it's consistently working on different Android devices.

**Comment by arman-tdev** [comment]
> Hi @arman-tdev / @navin9584 cc: @harish-challa
> 
> Please have a call to see why it's not working when Naivn is testing. we need to test on multiple devices and emulators to make sure it's consistently working on different Android devices.

Android version 9, 10 and 11th i have tested its working

**Comment by apurvabisht97** [comment]
hi @harish-challa @dileep-gadiraju  i have tested this pr . This pr is working as expected . We can merge this pr.

**Pull request merged**
